/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import br.com.j_fborges.dao.ConsumerMapDAO;
import br.com.j_fborges.dao.IConsumerDAO;
import br.com.j_fborges.dao.generic.IGenericDAO;
import br.com.j_fborges.domain.Consumer;
import br.com.j_fborges.domain.Persistent;
import br.com.j_fborges.exception.InvalidDataException;
import br.com.j_fborges.exception.TypeKeyNotFoundException;
import br.com.j_fborges.factory.Factory;
import br.com.j_fborges.factory.IFactory;
import br.com.j_fborges.factory.PersistentFactory;
import br.com.j_fborges.service.ConsumerService;
import br.com.j_fborges.service.IConsumerService;
import br.com.j_fborges.service.generic.IGenericService;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 * @author root
 */
public class ConsumerRegistrationTable extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsumerRegistrationTable.class.getName());
    private final IConsumerDAO iConsumerDAO;
    private final IConsumerService consumerService;

    private Integer selectedRow;
    private Boolean isUpdatingRow = false;

    public Boolean getIsUpdatingRow() {
        return isUpdatingRow;
    }

    public void setIsUpdatingRow(Boolean isUpdatingRow) {
        this.isUpdatingRow = isUpdatingRow;
    }

    public Integer getSelectedRow() {
        return selectedRow;
    }

    public void setSelectedRow(Integer selectedRow) {
        this.selectedRow = selectedRow;
    }

    private DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form ConsumerRegistrationTable
     */
    public ConsumerRegistrationTable() {
        initComponents();
        initCustomComponents();

        this.iConsumerDAO = new ConsumerMapDAO();
        this.consumerService = new ConsumerService(this.iConsumerDAO);
//        this.consumerDAO = new ConsumerSetDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsumerName = new javax.swing.JLabel();
        inputConsumerName = new javax.swing.JTextField();
        lblConsumerIdNumber = new javax.swing.JLabel();
        inputConsumerIdNumber = new javax.swing.JTextField();
        lblConsumerTel = new javax.swing.JLabel();
        inputConsumerTel = new javax.swing.JTextField();
        lblConsumerAddress = new javax.swing.JLabel();
        inputConsumerAddress = new javax.swing.JTextField();
        lblConsumerAddressNumber = new javax.swing.JLabel();
        inputConsumerAddressNumber = new javax.swing.JTextField();
        lblConsumerCity = new javax.swing.JLabel();
        inputConsumerCity = new javax.swing.JTextField();
        lblConsumerState = new javax.swing.JLabel();
        inputConsumerState = new javax.swing.JTextField();
        btnRegisterConsumer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsumer = new javax.swing.JTable();
        btnClearFields = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConsumerName.setText("Name:");

        inputConsumerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerNameActionPerformed(evt);
            }
        });

        lblConsumerIdNumber.setText("IdNumber:");

        inputConsumerIdNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerIdNumberActionPerformed(evt);
            }
        });

        lblConsumerTel.setText("Telephone:");

        lblConsumerAddress.setText("Address:");

        inputConsumerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerAddressActionPerformed(evt);
            }
        });

        lblConsumerAddressNumber.setText("Number:");

        inputConsumerAddressNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerAddressNumberActionPerformed(evt);
            }
        });

        lblConsumerCity.setText("City:");

        inputConsumerCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerCityActionPerformed(evt);
            }
        });

        lblConsumerState.setText("State:");

        inputConsumerState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerStateActionPerformed(evt);
            }
        });

        btnRegisterConsumer.setText("Register");
        btnRegisterConsumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnRegisterConsumerActionPerformed(evt);
                } catch (TypeKeyNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        tblConsumer.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
                }
        ));
        tblConsumer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsumerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblConsumer);

        btnClearFields.setText("Clear");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblConsumerTel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(inputConsumerTel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblConsumerIdNumber)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(inputConsumerIdNumber))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblConsumerName)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(inputConsumerName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(lblConsumerAddress)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(inputConsumerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(lblConsumerAddressNumber)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(inputConsumerAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(lblConsumerCity)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(inputConsumerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(lblConsumerState)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(inputConsumerState)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnClearFields)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnRegisterConsumer)))))
                                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblConsumerName)
                                        .addComponent(inputConsumerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblConsumerAddress)
                                        .addComponent(inputConsumerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblConsumerAddressNumber)
                                        .addComponent(inputConsumerAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblConsumerIdNumber)
                                        .addComponent(inputConsumerIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblConsumerCity)
                                        .addComponent(inputConsumerCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblConsumerState)
                                        .addComponent(inputConsumerState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblConsumerTel)
                                        .addComponent(inputConsumerTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRegisterConsumer)
                                        .addComponent(btnClearFields))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Exit application?", "Exit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void inputConsumerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerNameActionPerformed

    private void inputConsumerIdNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerIdNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerIdNumberActionPerformed

    private void inputConsumerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerAddressActionPerformed

    private void inputConsumerAddressNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerAddressNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerAddressNumberActionPerformed

    private void inputConsumerCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerCityActionPerformed

    private void inputConsumerStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerStateActionPerformed

    private void btnRegisterConsumerActionPerformed(java.awt.event.ActionEvent evt) throws TypeKeyNotFoundException, InvalidDataException {//GEN-FIRST:event_btnRegisterConsumerActionPerformed

        try {
            updateTable();

        } catch (TypeKeyNotFoundException e) {
            JOptionPane.showMessageDialog(null, "SYSTEM ERROR, CONTACT ADMINISTRATOR", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } catch (InvalidDataException e) {
            JOptionPane.showMessageDialog(null, "All Fields are mandatory.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterConsumerActionPerformed

    private void tblConsumerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsumerMouseClicked

        setSelectedRow(tblConsumer.getSelectedRow());

        Long idNumber = (Long) tblConsumer.getValueAt(getSelectedRow(), 1);

        Consumer consumer = this.iConsumerDAO.find(idNumber);

        if (consumer != null) {
            inputConsumerName.setText(consumer.getName());
            inputConsumerIdNumber.setText(consumer.getIdNumber().toString());
            inputConsumerTel.setText(consumer.getTel().toString());
            inputConsumerAddress.setText(consumer.getAddress());
            inputConsumerAddressNumber.setText(consumer.getAddressNumber().toString());
            inputConsumerCity.setText(consumer.getCity());
            inputConsumerState.setText(consumer.getState());

            btnRegisterConsumer.setText("Update");
            btnClearFields.setText("Delete");
            setIsUpdatingRow(true);
        }
    }//GEN-LAST:event_tblConsumerMouseClicked

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        if (isUpdatingRow) {

            int result = JOptionPane.showConfirmDialog(this, "Do you really want to delete this consumer from record?", "WARNING",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {

                Long idNumber = (Long) tblConsumer.getValueAt(getSelectedRow(), 1);
                this.iConsumerDAO.destroy(idNumber);
                model.removeRow(getSelectedRow());
                btnRegisterConsumer.setText("Register");
                btnClearFields.setText("Clear");
                setIsUpdatingRow(false);
                setSelectedRow(null);
                clearFields();

                JOptionPane.showMessageDialog(null, "Consumer record deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {

                btnRegisterConsumer.setText("Register");
                btnClearFields.setText("Clear");
                setIsUpdatingRow(false);
                setSelectedRow(null);
                clearFields();
            }

        } else {
            clearFields();
        }
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsumerRegistrationTable().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnRegisterConsumer;
    private javax.swing.JTextField inputConsumerAddress;
    private javax.swing.JTextField inputConsumerAddressNumber;
    private javax.swing.JTextField inputConsumerCity;
    private javax.swing.JTextField inputConsumerIdNumber;
    private javax.swing.JTextField inputConsumerName;
    private javax.swing.JTextField inputConsumerState;
    private javax.swing.JTextField inputConsumerTel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsumerAddress;
    private javax.swing.JLabel lblConsumerAddressNumber;
    private javax.swing.JLabel lblConsumerCity;
    private javax.swing.JLabel lblConsumerIdNumber;
    private javax.swing.JLabel lblConsumerName;
    private javax.swing.JLabel lblConsumerState;
    private javax.swing.JLabel lblConsumerTel;
    private javax.swing.JTable tblConsumer;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        RegistrationTableController.clearFields(inputConsumerName, inputConsumerIdNumber, inputConsumerTel, inputConsumerAddress, inputConsumerAddressNumber, inputConsumerCity, inputConsumerState);
    }

    private void initCustomComponents() {
        model.addColumn("Name");
        model.addColumn("id Number");
        model.addColumn("Telephone");
        model.addColumn("Address");
        model.addColumn("Address Number");
        model.addColumn("City");
        model.addColumn("State");

        tblConsumer.setModel(model);
    }

    private Boolean areInputsValid(String... inputs) {
        for (String input : inputs) {
            if (input == null || "".equals(input)) {
                return false;
            }
        }
        return true;
    }

    private Persistent genObjectEntry(String[] dadosSeparados, String opcaoMenuGeral) {
        IFactory factory = new Factory();
        PersistentFactory persistentFactory = factory.createFactory(opcaoMenuGeral);
        return persistentFactory.createObject(dadosSeparados);
    }

    String[] getCurrentFormFields() throws InvalidDataException {
        ArrayList<String> currentFormFields = new ArrayList<>();

        //if current form is consumer`s do the following:
        currentFormFields.add(inputConsumerName.getText());
        currentFormFields.add(inputConsumerIdNumber.getText());
        currentFormFields.add(inputConsumerTel.getText());
        currentFormFields.add(inputConsumerAddress.getText());
        currentFormFields.add(inputConsumerAddressNumber.getText());
        currentFormFields.add(inputConsumerCity.getText());
        currentFormFields.add(inputConsumerState.getText());
        //TODO: create differentiating clausules and checks for different objects

        if (areInputsValid(currentFormFields.toArray(new String[0]))) {
            return currentFormFields.toArray(new String[0]);
        } else {
            throw new InvalidDataException("All fields are mandatory!");
        }
    }

    public IGenericService getMatchingService() {
        //TODO: create differentiating clausules for different objects Servicess
        return consumerService;
    }

    public void addPersistentEntryAsRow(Persistent persistent) {
        //if current form is consumer`s do the following:
        Consumer consumer = (Consumer) persistent;
        model.addRow(new Object[]{consumer.getName(), consumer.getIdNumber(), consumer.getTel(), consumer.getAddress(), consumer.getAddressNumber(), consumer.getCity(), consumer.getState()});
        //TODO: create differentiating clausules and checks for different objects
    }

    public void updateTable() throws TypeKeyNotFoundException, InvalidDataException {

        if (isUpdatingRow) {
            Persistent persistent = genObjectEntry(getCurrentFormFields(), "Ofcourse");


            getMatchingService().update(persistent);

            model.removeRow(getSelectedRow());
            addPersistentEntryAsRow(persistent);
            btnRegisterConsumer.setText("Register");
            btnClearFields.setText("Clear");
            setIsUpdatingRow(false);
            setSelectedRow(null);
            clearFields();

        } else {

            Persistent persistent = genObjectEntry(getCurrentFormFields(), "Ofcourse");

            Boolean isRegistered = getMatchingService().register(persistent);

            if (isRegistered) {
                addPersistentEntryAsRow(persistent);
                clearFields();
            } else {
                JOptionPane.showMessageDialog(null, "Consumer is already registered", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

}
