/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import br.com.j_fborges.dao.ConsumerDAO;
import br.com.j_fborges.dao.IConsumerDAO;
import br.com.j_fborges.dao.IProductDAO;
import br.com.j_fborges.dao.ProductDAO;
import br.com.j_fborges.domain.Consumer;
import br.com.j_fborges.domain.Persistent;
import br.com.j_fborges.domain.Product;
import br.com.j_fborges.exception.InvalidDataException;
import br.com.j_fborges.exception.TypeKeyNotFoundException;
import br.com.j_fborges.factory.Factory;
import br.com.j_fborges.factory.IFactory;
import br.com.j_fborges.factory.PersistentFactory;
import br.com.j_fborges.service.ConsumerService;
import br.com.j_fborges.service.IConsumerService;
import br.com.j_fborges.service.IProductService;
import br.com.j_fborges.service.ProductService;
import br.com.j_fborges.service.generic.IGenericService;
import java.awt.CardLayout;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JTable;

/**
 * @author root
 */
public class ConsumerRegistrationTable extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsumerRegistrationTable.class.getName());
    private final IConsumerDAO iConsumerDAO;
    private final IConsumerService consumerService;

    private final IProductDAO iProductDAO;
    private final IProductService productService;

    public Long getSelectedPersistentId() {
        return selectedPersistentId;
    }

    public void setSelectedPersistentId(Long selectedPersistentId) {
        this.selectedPersistentId = selectedPersistentId;
    }

    private Long selectedPersistentId;
    private Integer selectedRow;
    private Boolean isUpdatingRow = false;
    private Boolean isConsumerForm = true;

    public Boolean getIsUpdatingRow() {
        return isUpdatingRow;
    }

    public void setIsUpdatingRow(Boolean isUpdatingRow) {
        this.isUpdatingRow = isUpdatingRow;
    }

    public void setIsConsumerForm(Boolean isConsumerForm) {
        this.isConsumerForm = isConsumerForm;
    }

    public Integer getSelectedRow() {
        return selectedRow;
    }

    public void setSelectedRow(Integer selectedRow) {
        this.selectedRow = selectedRow;
    }

    private DefaultTableModel model = new DefaultTableModel();
    private DefaultTableModel productTblModel = new DefaultTableModel();

    /**
     * Creates new form ConsumerRegistrationTable
     */
    public ConsumerRegistrationTable() {
        initComponents();
        initCustomComponents();

        this.iConsumerDAO = new ConsumerDAO();
        this.consumerService = new ConsumerService(this.iConsumerDAO);

        this.iProductDAO = new ProductDAO();
        this.productService = new ProductService(this.iProductDAO);

        ConsumerService consumerSrv = (ConsumerService) this.consumerService;
        Collection<Consumer> consumers = consumerSrv.loadConsumers();

        for(Consumer c : consumers){
            addPersistentEntryAsRow(c);
        }

        setIsConsumerForm(false);

        ProductService productSrv = (ProductService) this.productService;
        Collection<Product> products = productSrv.loadProducts();

        for(Product p : products){
            addPersistentEntryAsRow(p);
        }

        setIsConsumerForm(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAppHeader = new javax.swing.JPanel();
        pageHeading = new javax.swing.JLabel();
        jButtonPaging0 = new javax.swing.JButton();
        appHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegisterConsumer = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        jPanelAppPages = new javax.swing.JPanel();
        jPanelConsumer = new javax.swing.JPanel();
        inputConsumerAddressNumber = new javax.swing.JTextField();
        lblConsumerCity = new javax.swing.JLabel();
        inputConsumerCity = new javax.swing.JTextField();
        lblConsumerState = new javax.swing.JLabel();
        inputConsumerState = new javax.swing.JTextField();
        lblConsumerName = new javax.swing.JLabel();
        inputConsumerName = new javax.swing.JTextField();
        lblConsumerIdNumber = new javax.swing.JLabel();
        inputConsumerIdNumber = new javax.swing.JTextField();
        lblConsumerTel = new javax.swing.JLabel();
        inputConsumerTel = new javax.swing.JTextField();
        lblConsumerAddress = new javax.swing.JLabel();
        inputConsumerAddress = new javax.swing.JTextField();
        lblConsumerAddressNumber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsumer = new javax.swing.JTable();
        lblConsumerEmail = new javax.swing.JLabel();
        inputConsumerEmail = new javax.swing.JTextField();
        jPanelProduct = new javax.swing.JPanel();
        lblProductTitle = new javax.swing.JLabel();
        inputProductTitle = new javax.swing.JTextField();
        lblProductIdCode = new javax.swing.JLabel();
        inputProductIdCode = new javax.swing.JTextField();
        lblProductValue = new javax.swing.JLabel();
        inputProductValue = new javax.swing.JTextField();
        lblProductDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputProductDescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        lblProductCategory = new javax.swing.JLabel();
        inputProductCategory = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pageHeading.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        pageHeading.setText("Consumers");

        jButtonPaging0.setText("Products");
        jButtonPaging0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaging0ActionPerformed(evt);
            }
        });

        appHeading.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        appHeading.setText("StoreManagement");

        btnRegisterConsumer.setText("Register");
        btnRegisterConsumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterConsumerActionPerformed(evt);
            }
        });

        btnClearFields.setText("Clear");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAppHeaderLayout = new javax.swing.GroupLayout(jPanelAppHeader);
        jPanelAppHeader.setLayout(jPanelAppHeaderLayout);
        jPanelAppHeaderLayout.setHorizontalGroup(
            jPanelAppHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelAppHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAppHeaderLayout.createSequentialGroup()
                        .addComponent(appHeading)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonPaging0))
                    .addGroup(jPanelAppHeaderLayout.createSequentialGroup()
                        .addComponent(pageHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearFields)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisterConsumer))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAppHeaderLayout.setVerticalGroup(
            jPanelAppHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAppHeaderLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanelAppHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appHeading)
                    .addComponent(jButtonPaging0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanelAppHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterConsumer)
                    .addComponent(btnClearFields))
                .addGap(12, 12, 12))
        );

        jPanelAppPages.setLayout(new java.awt.CardLayout());

        jPanelConsumer.setBackground(new java.awt.Color(250, 250, 250));

        inputConsumerAddressNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerAddressNumberActionPerformed(evt);
            }
        });

        lblConsumerCity.setText("City:");

        inputConsumerCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerCityActionPerformed(evt);
            }
        });

        lblConsumerState.setText("State:");

        inputConsumerState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerStateActionPerformed(evt);
            }
        });

        lblConsumerName.setText("Name:");

        inputConsumerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerNameActionPerformed(evt);
            }
        });

        lblConsumerIdNumber.setText("IdNumber:");

        inputConsumerIdNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerIdNumberActionPerformed(evt);
            }
        });

        lblConsumerTel.setText("Telephone:");

        lblConsumerAddress.setText("Address:");

        inputConsumerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConsumerAddressActionPerformed(evt);
            }
        });

        lblConsumerAddressNumber.setText("Number:");

        tblConsumer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tblConsumer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsumerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblConsumer);

        lblConsumerEmail.setText("Email:");

        javax.swing.GroupLayout jPanelConsumerLayout = new javax.swing.GroupLayout(jPanelConsumer);
        jPanelConsumer.setLayout(jPanelConsumerLayout);
        jPanelConsumerLayout.setHorizontalGroup(
            jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsumerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConsumerLayout.createSequentialGroup()
                        .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelConsumerLayout.createSequentialGroup()
                                .addComponent(lblConsumerTel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputConsumerTel))
                            .addGroup(jPanelConsumerLayout.createSequentialGroup()
                                .addComponent(lblConsumerName)
                                .addGap(18, 18, 18)
                                .addComponent(inputConsumerName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelConsumerLayout.createSequentialGroup()
                                .addComponent(lblConsumerEmail)
                                .addGap(18, 18, 18)
                                .addComponent(inputConsumerEmail)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsumerLayout.createSequentialGroup()
                                .addComponent(lblConsumerIdNumber)
                                .addGap(18, 18, 18)
                                .addComponent(inputConsumerIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelConsumerLayout.createSequentialGroup()
                                .addComponent(lblConsumerCity)
                                .addGap(18, 18, 18)
                                .addComponent(inputConsumerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblConsumerState)
                                .addGap(18, 18, 18)
                                .addComponent(inputConsumerState, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelConsumerLayout.createSequentialGroup()
                                .addComponent(lblConsumerAddress)
                                .addGap(18, 18, 18)
                                .addComponent(inputConsumerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblConsumerAddressNumber)
                                .addGap(18, 18, 18)
                                .addComponent(inputConsumerAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanelConsumerLayout.setVerticalGroup(
            jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsumerLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsumerName)
                    .addComponent(inputConsumerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsumerIdNumber)
                    .addComponent(inputConsumerIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsumerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConsumerTel)
                            .addComponent(inputConsumerTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsumerEmail)
                        .addComponent(inputConsumerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConsumerLayout.createSequentialGroup()
                        .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConsumerAddress)
                            .addComponent(inputConsumerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConsumerAddressNumber)
                            .addComponent(inputConsumerAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConsumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConsumerCity)
                            .addComponent(inputConsumerCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConsumerState)
                            .addComponent(inputConsumerState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanelAppPages.add(jPanelConsumer, "card2");

        lblProductTitle.setText("Title:");

        inputProductTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProductTitleActionPerformed(evt);
            }
        });

        lblProductIdCode.setText("IdCode:");

        inputProductIdCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProductIdCodeActionPerformed(evt);
            }
        });

        lblProductValue.setText("Value:");

        lblProductDescription.setText("Description:");

        inputProductDescription.setColumns(20);
        inputProductDescription.setRows(5);
        jScrollPane2.setViewportView(inputProductDescription);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblProduct);

        lblProductCategory.setText("Category:");

        javax.swing.GroupLayout jPanelProductLayout = new javax.swing.GroupLayout(jPanelProduct);
        jPanelProduct.setLayout(jPanelProductLayout);
        jPanelProductLayout.setHorizontalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblProductDescription)
                        .addGroup(jPanelProductLayout.createSequentialGroup()
                            .addComponent(lblProductIdCode)
                            .addGap(18, 18, 18)
                            .addComponent(inputProductIdCode, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblProductTitle)
                            .addGap(18, 18, 18)
                            .addComponent(inputProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblProductValue)
                            .addGap(18, 18, 18)
                            .addComponent(inputProductValue, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblProductCategory)
                            .addGap(18, 18, 18)
                            .addComponent(inputProductCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanelProductLayout.setVerticalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductTitle)
                    .addComponent(inputProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductIdCode)
                    .addComponent(inputProductIdCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductValue)
                    .addComponent(inputProductValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductCategory)
                    .addComponent(inputProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblProductDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanelAppPages.add(jPanelProduct, "card3");

        jMenu1.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAppPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(jPanelAppHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAppHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAppPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Exit application?", "Exit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void inputConsumerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerNameActionPerformed

    private void inputConsumerIdNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerIdNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerIdNumberActionPerformed

    private void inputConsumerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerAddressActionPerformed

    private void inputConsumerAddressNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerAddressNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerAddressNumberActionPerformed

    private void inputConsumerCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerCityActionPerformed

    private void inputConsumerStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConsumerStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConsumerStateActionPerformed

    private void btnRegisterConsumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterConsumerActionPerformed

        try {
            updateTable(getMatchingModel(), getMatchingModelName());

        } catch (TypeKeyNotFoundException e) {
            JOptionPane.showMessageDialog(null, "SYSTEM ERROR, CONTACT ADMINISTRATOR", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } catch (InvalidDataException e) {
            JOptionPane.showMessageDialog(null, "All Fields are mandatory.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterConsumerActionPerformed

    private void tblConsumerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsumerMouseClicked
        getCurrentSelectedPersistent(tblConsumer);
    }//GEN-LAST:event_tblConsumerMouseClicked

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        if (isUpdatingRow) {

            String currentPersistentString = getMatchingModelName();

            int result = JOptionPane.showConfirmDialog(this, "Do you really want to delete this " + currentPersistentString.toLowerCase() + " from record?", "WARNING",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {

                deleteCurrentSelectedPersistent();

                JOptionPane.showMessageDialog(null, currentPersistentString + " record deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {

                btnRegisterConsumer.setText("Register");
                btnClearFields.setText("Clear");
                setIsUpdatingRow(false);
                setSelectedRow(null);
                setSelectedPersistentId(null);
                clearFields();
            }

        } else {
            clearFields();
        }
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void jButtonPaging0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaging0ActionPerformed
        CardLayout cl = (CardLayout) jPanelAppPages.getLayout();

        btnRegisterConsumer.setText("Register");
        btnClearFields.setText("Clear");
        setIsUpdatingRow(false);
        setSelectedRow(null);
        setSelectedPersistentId(null);
        clearFields();

        if (isConsumerForm) {
            cl.show(jPanelAppPages, "card3");
            jButtonPaging0.setText("Consumers");
            pageHeading.setText("Products");

            setIsConsumerForm(false);
        } else {
            cl.show(jPanelAppPages, "card2");
            jButtonPaging0.setText("Products");
            pageHeading.setText("Consumers");
            setIsConsumerForm(true);
        }
    }//GEN-LAST:event_jButtonPaging0ActionPerformed

    private void inputProductTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProductTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputProductTitleActionPerformed

    private void inputProductIdCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProductIdCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputProductIdCodeActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        getCurrentSelectedPersistent(tblProduct);
    }//GEN-LAST:event_tblProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsumerRegistrationTable().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appHeading;
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnRegisterConsumer;
    private javax.swing.JTextField inputConsumerAddress;
    private javax.swing.JTextField inputConsumerAddressNumber;
    private javax.swing.JTextField inputConsumerCity;
    private javax.swing.JTextField inputConsumerEmail;
    private javax.swing.JTextField inputConsumerIdNumber;
    private javax.swing.JTextField inputConsumerName;
    private javax.swing.JTextField inputConsumerState;
    private javax.swing.JTextField inputConsumerTel;
    private javax.swing.JTextField inputProductCategory;
    private javax.swing.JTextArea inputProductDescription;
    private javax.swing.JTextField inputProductIdCode;
    private javax.swing.JTextField inputProductTitle;
    private javax.swing.JTextField inputProductValue;
    private javax.swing.JButton jButtonPaging0;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JPanel jPanelAppHeader;
    private javax.swing.JPanel jPanelAppPages;
    private javax.swing.JPanel jPanelConsumer;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConsumerAddress;
    private javax.swing.JLabel lblConsumerAddressNumber;
    private javax.swing.JLabel lblConsumerCity;
    private javax.swing.JLabel lblConsumerEmail;
    private javax.swing.JLabel lblConsumerIdNumber;
    private javax.swing.JLabel lblConsumerName;
    private javax.swing.JLabel lblConsumerState;
    private javax.swing.JLabel lblConsumerTel;
    private javax.swing.JLabel lblProductCategory;
    private javax.swing.JLabel lblProductDescription;
    private javax.swing.JLabel lblProductIdCode;
    private javax.swing.JLabel lblProductTitle;
    private javax.swing.JLabel lblProductValue;
    private javax.swing.JLabel pageHeading;
    private javax.swing.JTable tblConsumer;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        if (isConsumerForm) {
            RegistrationTableController.clearFields(inputConsumerName, inputConsumerIdNumber, inputConsumerEmail, inputConsumerTel, inputConsumerAddress, inputConsumerAddressNumber, inputConsumerCity, inputConsumerState);
        } else {
            RegistrationTableController.clearFields(inputProductTitle, inputProductIdCode, inputProductValue, inputProductCategory, inputProductDescription);
        }
    }

    private void initCustomComponents() {
        model.addColumn("Id");
        model.addColumn("Name");
        model.addColumn("Id Number");
        model.addColumn("Email");
        model.addColumn("Telephone");
        model.addColumn("Address");
        model.addColumn("Address Number");
        model.addColumn("City");
        model.addColumn("State");

        tblConsumer.setModel(model);

        productTblModel.addColumn("Id");
        productTblModel.addColumn("Title");
        productTblModel.addColumn("Id Code");
        productTblModel.addColumn("Value");
        productTblModel.addColumn("Category");
        productTblModel.addColumn("Description");

        tblProduct.setModel(productTblModel);
    }

    private Boolean areInputsValid(String... inputs) {
        for (String input : inputs) {
            if (input == null || "".equals(input)) {
                return false;
            }
        }
        return true;
    }

    private Persistent genMatchingObjectEntry(String[] dadosSeparados, String opcaoMenuGeral) {
        IFactory factory = new Factory();
        PersistentFactory persistentFactory = factory.createFactory(opcaoMenuGeral);
        return persistentFactory.createObject(dadosSeparados);
    }

    String[] getCurrentFormFields() throws InvalidDataException {
        ArrayList<String> currentFormFields = new ArrayList<>();

        if (isConsumerForm) {
            if(isUpdatingRow){
                currentFormFields.add(getSelectedPersistentId().toString());
            } else {
                IGenericService srv = getMatchingService();
                Long nextVal = (srv.loadCurrSequenceIdKey() + 1);
                currentFormFields.add(nextVal.toString());
            }
            currentFormFields.add(inputConsumerName.getText());
            currentFormFields.add(inputConsumerIdNumber.getText());
            currentFormFields.add(inputConsumerEmail.getText());
            currentFormFields.add(inputConsumerTel.getText());
            currentFormFields.add(inputConsumerAddress.getText());
            currentFormFields.add(inputConsumerAddressNumber.getText());
            currentFormFields.add(inputConsumerCity.getText());
            currentFormFields.add(inputConsumerState.getText());
        } else {
            if(isUpdatingRow){
                currentFormFields.add(getSelectedPersistentId().toString());
            } else {
                IGenericService srv = getMatchingService();
                Long nextVal = (srv.loadCurrSequenceIdKey() + 1);
                currentFormFields.add(nextVal.toString());
            }
            currentFormFields.add(inputProductTitle.getText());
            currentFormFields.add(inputProductIdCode.getText());
            currentFormFields.add(inputProductValue.getText());
            currentFormFields.add(inputProductCategory.getText());
            currentFormFields.add(inputProductDescription.getText());
        }

        //TODO: create differentiating clausules and checks for different objects
        if (areInputsValid(currentFormFields.toArray(new String[0]))) {
            return currentFormFields.toArray(new String[0]);
        } else {
            throw new InvalidDataException("All fields are mandatory!");
        }
    }

    public IGenericService getMatchingService() {
        //TODO: create differentiating clausules for different objects Servicess
        return isConsumerForm ? consumerService : productService;
    }

    public DefaultTableModel getMatchingModel() {
        return isConsumerForm ? model : productTblModel;
    }

    public String getMatchingModelName() {
        return isConsumerForm ? "Consumer" : "Product";
    }

    public JTable getMatchingTable() {
        return isConsumerForm ? tblConsumer : tblProduct;
    }

    public Persistent getMatchingPersistentByIdKey() {
        if (isConsumerForm) {
            Long id = (Long) tblConsumer.getValueAt(getSelectedRow(), 0);

            Consumer consumer = this.consumerService.find(id);

            return consumer;
        } else {
            Long id = (Long) tblProduct.getValueAt(getSelectedRow(), 0);
            Product product = this.productService.find(id);
            return product;
        }
    }

    public void fillMatchingPersistentFields(Persistent persistent) {
        if (isConsumerForm) {
            Consumer consumer = (Consumer) persistent;

            inputConsumerName.setText(consumer.getName());
            inputConsumerIdNumber.setText(consumer.getIdNumber().toString());
            inputConsumerEmail.setText(consumer.getEmail());
            inputConsumerTel.setText(consumer.getTel().toString());
            inputConsumerAddress.setText(consumer.getAddress());
            inputConsumerAddressNumber.setText(consumer.getAddressNumber().toString());
            inputConsumerCity.setText(consumer.getCity());
            inputConsumerState.setText(consumer.getState());
        } else {
            Product product = (Product) persistent;

            inputProductTitle.setText(product.getTitle());
            inputProductIdCode.setText(product.getIdCode());
            inputProductValue.setText(product.getPrice().toString());
            inputProductCategory.setText(product.getCategory());
            inputProductDescription.setText(product.getDescription());
        }
    }

    public void addPersistentEntryAsRow(Persistent persistent) {
        //if current form is consumer`s do the following:
        if (isConsumerForm) {
            Consumer consumer = (Consumer) persistent;
            model.addRow(new Object[]{consumer.getId(), consumer.getName(), consumer.getIdNumber(), consumer.getEmail(), consumer.getTel(), consumer.getAddress(), consumer.getAddressNumber(), consumer.getCity(), consumer.getState()});
            //TODO: create differentiating clausules and checks for different objects
        } else {
            Product product = (Product) persistent;
            productTblModel.addRow(new Object[]{product.getId(), product.getTitle(), product.getIdCode(), product.getPrice(), product.getCategory(), product.getDescription()});
        }
    }

    public void getCurrentSelectedPersistent(JTable tblPersistent) {
        setSelectedRow(tblPersistent.getSelectedRow());


        Persistent persistent = getMatchingPersistentByIdKey();
        setSelectedPersistentId(persistent.getId());

        if (persistent != null) {
            fillMatchingPersistentFields(persistent);

            btnRegisterConsumer.setText("Update");
            btnClearFields.setText("Delete");
            setIsUpdatingRow(true);
        }
    }

    public void deleteCurrentSelectedPersistent() {
        Persistent persistent = getMatchingPersistentByIdKey();
        DefaultTableModel model = getMatchingModel();

        if (isConsumerForm) {
            Consumer consumer = (Consumer) persistent;
            consumerService.delete(consumer.getId());
        } else {
            Product product = (Product) persistent;
            productService.delete(product.getId());
        }

        model.removeRow(getSelectedRow());
        btnRegisterConsumer.setText("Register");
        btnClearFields.setText("Clear");

        setIsUpdatingRow(false);
        setSelectedRow(null);
        clearFields();
    }

    public void updateTable(DefaultTableModel model, String tableObjectName) throws TypeKeyNotFoundException, InvalidDataException {

        if (isUpdatingRow) {
            Persistent persistent = genMatchingObjectEntry(getCurrentFormFields(), tableObjectName);

            getMatchingService().update(persistent);

            model.removeRow(getSelectedRow());
            addPersistentEntryAsRow(persistent);
            btnRegisterConsumer.setText("Register");
            btnClearFields.setText("Clear");
            setIsUpdatingRow(false);
            setSelectedRow(null);
            setSelectedPersistentId(null);
            clearFields();

        } else {

            Persistent persistent = genMatchingObjectEntry(getCurrentFormFields(), tableObjectName);

            Boolean isRegistered = false;

            try {
                isRegistered = getMatchingService().register(persistent);

            } catch (Exception e) {
                e.printStackTrace();
            }

            if (isRegistered) {
                addPersistentEntryAsRow(persistent);
                clearFields();
            } else {
                JOptionPane.showMessageDialog(null, tableObjectName + " is already registered", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

}
